### ISSUE TITLE
Support key-file

### ISSUE THREAD

**Issue by VonKavalier** [fopina/kdbxpasswordpwned#2]
I wanted to try the script on my password database, and got stuck because it only asks for the password.

It fails decryption if the database is protected with a key-file.

**Comment by fopina** [comment]
When I created the script I thought "if anyone finds this, they'll probably use a key-file unlike myself and complain. maybe they'll send a PR" :)

I'll take a look at it, `libkeepass' does support key files

**Comment by VonKavalier** [comment]
Haha :sweat_smile: Yeah sorry, I just thought that if it's not me it will be someone else ^^

**Comment by fopina** [comment]
fixed by #5
