### ISSUE TITLE
"Unknown header field found". Doesn't support latest database version?

### ISSUE THREAD

**Issue by FliegendeWurst** [fopina/kdbxpasswordpwned#4]

**Comment by fopina** [comment]
libkeepass states to support kdb4 format. could you create a test kdbx file in that tool and share it?

**Comment by FliegendeWurst** [comment]
You can download a database I created with KeepassXC here: https://www.file-upload.net/download-13482806/tmp.kdbx.html

It uses the new Argon2 KDF, password is 123456.
